# Generated by Django 5.2.11 on 2026-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
